version: '3.9'
services:
  stablediffusion-finetune:
    build: .
    ports:
    - 9999:9999
    volumes:
      - ./checkpoints/:/app/checkpoints
      - ./notebooks/:/app/notebooks
      - ./src/:/app/src
      - ./dataset/:/app/dataset
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]